# Generated by Django 3.0.3 on 2020-05-21 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_auto_20200423_1619'),
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.hourse')),
                ('ownUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownUser', to='login.User', verbose_name='房东')),
            ],
        ),
    ]
