# Generated by Django 3.0.3 on 2020-05-21 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200423_1619'),
        ('house', '0002_auto_20200521_1139'),
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentorder',
            name='ownUser',
        ),
        migrations.AddField(
            model_name='rentorder',
            name='rent_ownUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rent_ownUser', to='login.User', verbose_name='房东'),
        ),
        migrations.AddField(
            model_name='rentorder',
            name='rent_paidUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rent_paidUser', to='login.User', verbose_name='房客'),
        ),
        migrations.AlterField(
            model_name='rentorder',
            name='house',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='house.hourse'),
        ),
    ]
