# Generated by Django 3.0.3 on 2020-05-27 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20200527_1242'),
        ('rent', '0003_auto_20200521_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentorder',
            name='house',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='house.house'),
        ),
    ]
