# Generated by Django 3.0.3 on 2020-06-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_auto_20200527_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentorder',
            name='begintime',
            field=models.DateField(default=None, verbose_name='开始时间'),
        ),
    ]
