# Generated by Django 3.0.3 on 2020-06-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_rentorder_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentorder',
            name='money',
            field=models.IntegerField(default=0, verbose_name='金额'),
        ),
    ]
