# Generated by Django 3.0.3 on 2020-04-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('Username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mod_data', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
