# Generated by Django 3.0.3 on 2020-05-21 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_auto_20200423_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='hourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoursename', models.CharField(max_length=32)),
                ('area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('location', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('single', '单人间'), ('double', '双人间'), ('triple', '三人间'), ('quad', '四人间')], max_length=32)),
                ('orientation', models.CharField(choices=[('north', '北'), ('east', '东'), ('west', '西'), ('south', '南')], max_length=32, verbose_name='朝向')),
                ('rental', models.IntegerField(verbose_name='租金')),
                ('elevator', models.BooleanField()),
                ('introduction', models.CharField(default='暂无简介', max_length=256, verbose_name='简介')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
    ]
