# Generated by Django 3.0.3 on 2020-05-27 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repair', '0004_auto_20200527_1242'),
        ('house', '0003_auto_20200527_1242'),
        ('login', '0002_auto_20200423_1619'),
        ('rent', '0004_auto_20200527_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hourse',
        ),
        migrations.AddField(
            model_name='house',
            name='User',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
